export default {
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
  SEARCH_VIDEOS_SUCCESS: 'SEARCH_VIDEOS_SUCCESS',
  SEARCH_NEXT_PAGE: 'SEARCH_NEXT_PAGE',
  ADD_FAVORITE_VIDEO: 'ADD_FAVORITE_VIDEO',
  REMOVE_FAVORITE_VIDEO: 'REMOVE_FAVORITE_VIDEO'
}
